global: 
  scrape_interval: 15s   # Интервал опроса метрик 
scrape_configs: 
  - job_name: 'docker' 
    static_configs: 
      - targets: ['web:5000']  # Цель для сбора метрик — сервис web на порту 5000